apiVersion: v1
kind: Pod
metadata:
 name: alpha-zero
 namespace: default
spec:
 hostNetwork: true
 containers:
 - name: alpha-zero
   image: docker.io/nvidia/cuda:12.2.2-devel-torch
   imagePullPolicy: Never
   command: [ "/bin/bash", "-c", "--" ]       # You need to run some task inside a container to keep it running
   args: [ "while true; do sleep 10; done;" ]
 restartPolicy: Never
 tolerations:
 - key: "key"
   operator: "Exists"
   effect: "NoSchedule"
