apiVersion: v1
kind: Pod
metadata:
 name: fedora-devel-worknode
 namespace: default
spec:
 #hostNetwork: true
 hostIPC: true
 nodeName: vfanny
 containers:
 - name: fedora-devel
   #image: docker.io/library/fedora
   image: localhost/fedora-devel:v0.0.1
   imagePullPolicy: Never
   securityContext:
     privileged: true
   command: [ "/bin/bash", "-c", "--" ]       # You need to run some task inside a container to keep it running
   args: [ "while true; do sleep 10; done;" ]
 restartPolicy: Never
 tolerations:
 - key: "key"
   operator: "Exists"
   effect: "NoSchedule"
