apiVersion: v1
kind: Pod
metadata:
 name: fedora
 namespace: default
spec:
 hostNetwork: true
 hostIPC: true
 containers:
 - name: fedora
   image: docker.io/library/fedora
   imagePullPolicy: Never
   command: [ "/bin/bash", "-c", "--" ]       # You need to run some task inside a container to keep it running
   args: [ "while true; do sleep 10; done;" ]
 restartPolicy: Never
 tolerations:
 - key: "key"
   operator: "Exists"
   effect: "NoSchedule"
