apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-stable-diffusion
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/wyou/data/partition1/pvs/pv-stable-diffusion"
