apiVersion: v1
kind: Pod
metadata:
 name: stable-diffusion
 namespace: default
spec:
 hostNetwork: true
 hostIPC: true
 containers:
 - name: stable-diffusion
   image: localhost/diffuser-pytorch-cuda:v0.0.3
   imagePullPolicy: Never
   resources:
      limits:
        nvidia.com/gpu: 1
   command: [ "/bin/bash", "-c", "--" ]       # You need to run some task inside a container to keep it running
   args: [ "while true; do sleep 10; done;" ]
   volumeMounts:
   - name: stable-diffusion-storage
     mountPath: /home/stable-diffusion-storage
 volumes:
 - name: stable-diffusion-storage
   persistentVolumeClaim:
     claimName: pvc-stable-diffusion
 restartPolicy: Never
 tolerations:
 - key: "key"
   operator: "Exists"
   effect: "NoSchedule"
