apiVersion: v1
kind: Pod
metadata:
 name: ollama-base
 namespace: default
spec:
 hostNetwork: true
 hostIPC: true
 containers:
 - name: ollama-base
   image: docker.io/ollama/ollama
   imagePullPolicy: Never
   resources:
      limits:
        nvidia.com/gpu: 1
   command: [ "/bin/bash", "-c", "--" ]       # You need to run some task inside a container to keep it running
   args: [ "while true; do sleep 10; done;" ]
   volumeMounts:
   - name: ollama-storage
     mountPath: /root/.ollama
 volumes:
 - name: ollama-storage
   emptyDir: {}
 restartPolicy: Never
 tolerations:
 - key: "key"
   operator: "Exists"
   effect: "NoSchedule"
