apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ollama
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/wyou/data/partition1/pvs/pv-ollama"
